export enum dashboardTypes {
    FETCH_PERSON_REQUEST = "FETCH_PERSON_REQUEST",
    FETCH_PERSON_SUCCESS = "FETCH_PERSON_SUCCESS",
    FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST",
    FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
}
